CREATE TABLE employee (
  EId INT(11) NOT NULL AUTO_INCREMENT,
  EName VARCHAR(255) NOT NULL,
  EAddress VARCHAR(255) NOT NULL,
  EDistrict VARCHAR(255) NOT NULL,
  EExperience INT(2) NOT NULL DEFAULT 0,
  EBirthdate DATE NOT NULL,
  EMainLanguage VARCHAR(50) NOT NULL,
  EEducation VARCHAR(255),
  ECurrentSalary INT(11) NOT NULL,
  EPerks VARCHAR(255),
  EPhoto LONGBLOB,
  ENotes VARCHAR(255),
  PRIMARY KEY (EId)
);

CREATE TABLE customer (
  CId INT(11) NOT NULL AUTO_INCREMENT,
  CName VARCHAR(255) NOT NULL,
  CPhone VARCHAR(20) NOT NULL,
  CBank VARCHAR(255) NOT NULL,
  CInn VARCHAR(20) NOT NULL,
  CAddress VARCHAR(255),
  PRIMARY KEY (CId)
);

CREATE TABLE project (
  PId INT(11) NOT NULL AUTO_INCREMENT,
  PName VARCHAR(255) NOT NULL,
  PStartDate DATE NOT NULL,
  PEndDate DATE NOT NULL,
  PCost INT(11) NOT NULL,
  PLeaderEId INT(11) NOT NULL,
  CId INT(11) NOT NULL,
  PCRepresentativeName VARCHAR(255) NOT NULL,
  PCRepresentativePhone VARCHAR(20) NOT NULL,
  PBonusAmount INT(11) NOT NULL,
  PRIMARY KEY (PId),
  FOREIGN KEY (PLeaderEId) REFERENCES employee(EId) ON UPDATE CASCADE,
  FOREIGN KEY (CId) REFERENCES customer(CId) ON UPDATE CASCADE
);

CREATE TABLE employee_project (
  EId INT(11) NOT NULL,
  PId INT(11) NOT NULL,
  PRIMARY KEY (EId, PId),
  FOREIGN KEY (EId) REFERENCES employee(EId) ON UPDATE CASCADE,
  FOREIGN KEY (PId) REFERENCES project(PId) ON UPDATE CASCADE
);

CREATE TABLE employee_payment (
  EPId INT(11) NOT NULL AUTO_INCREMENT,
  EPDate DATE NOT NULL,
  EId INT(11) NOT NULL,
  EPAmount INT(11) NOT NULL,
  EPType VARCHAR(255) NOT NULL,
  PRIMARY KEY (EPId),
  FOREIGN KEY (EId) REFERENCES employee(EId) ON UPDATE CASCADE
);


